using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Komet.Rules;

// The files the rules apply to: the project's own sources, whatever their name or header says. Roslyn's generated-code heuristic
// (*.g.cs, *.designer.cs, a `// <auto-generated/>` header) is not used, so every analyzer asks for generated code and filters here.
// Skipped are paths outside the project directory and under its obj/ or bin/: the SDK's GlobalUsings.g.cs and AssemblyInfo.cs and
// every source generator's output (csc roots generated trees at its output directory, obj/<cfg>/<generator>/...). Without a project
// directory (a compilation outside MSBuild), a path with an obj or bin segment is skipped.
internal sealed class Sources
{
    private readonly HashSet<SyntaxTree> _user;

    private Sources(HashSet<SyntaxTree> user)
    {
        _user = user;
    }

    public static Sources Of(Compilation compilation, AnalyzerOptions options)
    {
        _ = options.AnalyzerConfigOptionsProvider.GlobalOptions.TryGetValue("build_property.projectdir", out var dir);
        var root = string.IsNullOrEmpty(dir) ? null : Normal(dir!).TrimEnd('/') + "/";
        return new Sources([.. compilation.SyntaxTrees.Where(tree => IsUser(Normal(tree.FilePath), root))]);
    }

    public Action<SyntaxTreeAnalysisContext> Tree(Action<SyntaxTreeAnalysisContext> action)
    {
        return c =>
        {
            if (_user.Contains(c.Tree)) action(c);
        };
    }

    public Action<SyntaxNodeAnalysisContext> Node(Action<SyntaxNodeAnalysisContext> action)
    {
        return c =>
        {
            if (_user.Contains(c.Node.SyntaxTree)) action(c);
        };
    }

    public Action<OperationAnalysisContext> Operation(Action<OperationAnalysisContext> action)
    {
        return c =>
        {
            if (_user.Contains(c.Operation.Syntax.SyntaxTree)) action(c);
        };
    }

    private static bool IsUser(string path, string? root)
    {
        if (root is null) return Array.TrueForAll(path.Split('/'), segment => segment is not ("obj" or "bin"));
        return path.StartsWith(root, StringComparison.OrdinalIgnoreCase) &&
               !path.StartsWith(root + "obj/", StringComparison.OrdinalIgnoreCase) &&
               !path.StartsWith(root + "bin/", StringComparison.OrdinalIgnoreCase);
    }

    private static string Normal(string path)
    {
        return path.Replace('\\', '/');
    }
}
